### ISSUE TITLE
is it right that this plugin is not asynchonous?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-legacysurvey#7]
is it right that this plugin is not asynchonous? The GW one is.

**Comment by dsavchenko** [comment]
That's right. I never saw the need for it to be asynchronous. All the jobs are fast. 
But it could easily be done async if needed.

**Comment by volodymyrss** [comment]
Indeed. But they still take few seconds occasionally - would be nice if "submitted" appeared.
For that, could this functionality be in a generic class, in a separate repo, and shared between gw, legacy survey, and other future similar instruments?

**Comment by volodymyrss** [comment]
once it transitions (whenever) to generic plugin this issue is irrelevant
